### ISSUE TITLE
difference in Bioconductor package and Github repo

### ISSUE THREAD

**Issue by AnitaS321** [PoisonAlien/maftools#643] opened 2020-12-11 18:10 UTC
The coBarplot() function is not available in the current Bioconductor repo for maftools. However, the Github repo has it. 
Conversely, the bug fix to annotate clinical features in oncoplot() is only in the Github repo.

**Comment by PoisonAlien** [comment] 2020-12-11 20:15
Hi,
Could you please post your `sessionInfo()`?  `coBarplot()` is definitely there on the BioConductor release and devel versions (since version `2.4.0`). It is also built and checked in the current [vignette](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#953_Co-bar_plots). Please make sure that the installed package version is `2.4` or above.

**Comment by AnitaS321** [comment] 2020-12-11 20:47
Hi, thanks for quick reply. I installed using `BiocManager::install("maftools")` and then installed using `BiocManager::install("PoisonAlien/maftools")` sessionInfo for both are below. Older version of maftools is auto-pulled from bioconductor. But newer version from GitHub repo doesn't seem to have the bug fix mentioned in issue [559](https://github.com/PoisonAlien/maftools/issues/599): which is why I re-installed from bioconductor. 

```R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.0.16     Biobase_2.44.0      BiocGenerics_0.30.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         plyr_1.8.6         pillar_1.4.6       compiler_3.6.3    
 [5] RColorBrewer_1.1-2 rngtools_1.5       iterators_1.0.12   tools_3.6.3       
 [9] digest_0.6.25      lattice_0.20-41    lifecycle_0.2.0    tibble_3.0.3      
[13] gtable_0.3.0       gridBase_0.4-7     NMF_0.23.0         pkgconfig_2.0.3   
[17] rlang_0.4.7        Matrix_1.2-18      foreach_1.5.0      bibtex_0.4.2.3    
[21] registry_0.5-1     rstudioapi_0.11    yaml_2.2.1         withr_2.3.0       
[25] dplyr_1.0.2        pkgmaker_0.31.1    stringr_1.4.0      cluster_2.1.0     
[29] generics_0.0.2     vctrs_0.3.4        wordcloud_2.6      grid_3.6.3        
[33] tidyselect_1.1.0   data.table_1.13.0  glue_1.4.2         R6_2.4.1          
[37] survival_3.2-3     reshape2_1.4.4     ggplot2_3.3.2      purrr_0.3.4       
[41] magrittr_1.5       splines_3.6.3      scales_1.1.1       codetools_0.2-16  
[45] ellipsis_0.3.1     assertthat_0.2.1   xtable_1.8-4       colorspace_1.4-1  
[49] stringi_1.5.3      doParallel_1.0.15  munsell_0.5.0      crayon_1.3.4``



```R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.6.05

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11     splines_3.6.3       lattice_0.20-41     R6_2.4.1           
 [5] fansi_0.4.1         tools_3.6.3         pkgbuild_1.1.0      grid_3.6.3         
 [9] data.table_1.13.0   cli_2.0.2           withr_2.3.0         remotes_2.2.0      
[13] yaml_2.2.1          survival_3.2-3      assertthat_0.2.1    rprojroot_1.3-2    
[17] crayon_1.3.4        processx_3.4.4      Matrix_1.2-18       BiocManager_1.30.10
[21] RColorBrewer_1.1-2  callr_3.4.4         ps_1.3.4            curl_4.3           
[25] glue_1.4.2          compiler_3.6.3      backports_1.1.10    prettyunits_1.1.1

**Comment by PoisonAlien** [comment] 2020-12-11 21:00
Uh-oh! I see the issue here. You're using an older R version `3.6` and the current BioConductor [release](https://www.bioconductor.org/about/release-announcements/) version is 3.12 which requires R `4.0`.
Using an older version of R means whenever you attempt to install a package from BioConductor, `BiocManager` will pull the package from its compatible BioConductor version. For your version of R,  packages from early 2019 will be installed. It's always good to keep versions up to date. 

Installing from GitHub can be much merciful as it doesn't care about `R` versions. Once you have installed from GitHub, could you please restart your R and try the plotting again? Fix from #559 should work.

**Comment by AnitaS321** [comment] 2020-12-11 21:10
Yes, I was actively trying to avoid updating R at the moment. Reinstalled from GitHub and restarted R but am still getting `Error in if (is.na(col)) { : argument is of length zero` detailed in issue 559.

```R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.6.05

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.10 compiler_3.6.3      Matrix_1.2-18       tools_3.6.3        
 [5] RColorBrewer_1.1-2  survival_3.2-3      curl_4.3            yaml_2.2.1         
 [9] remotes_2.2.0       splines_3.6.3       grid_3.6.3          data.table_1.13.0  
[13] lattice_0.20-41 ```

**Comment by PoisonAlien** [comment] 2020-12-11 21:13
Could you post your complete set of commands? It's quite late for me now, I will have a look in the morning.

**Comment by AnitaS321** [comment] 2020-12-11 21:26
Yes of course, thank you - I appreciate your help.

```
laml.maf = read.maf("ccf.maf",clinicalData = "ClinicalData.txt")
clonal<-subsetMaf(maf=laml.maf,query = "ccf_1copy_lower >= 0.70")
mycolors = RColorBrewer::brewer.pal(n = 10,name = 'Spectral')
names(mycolors)=c("Carcinoma","CNS","Germ Cell","Hepatoblastoma","Melanoma","Neuroblastoma","Retinoblastoma","Sarcoma","Wilms Tumor","Other")
mycolors = list(Disease_Category = mycolors)
oncoplot(maf = clonal, top = 20,clinicalFeatures = 'Disease_Category',sortByAnnotation = TRUE,annotationColor = mycolors)
```

**Comment by PoisonAlien** [comment] 2020-12-12 09:42
I have trouble reproducing the issue. I simulated an example dataset to mimic your clinical factors and it works fine on my system. Could you try the following commands? 

```r
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')
clin = data.table::fread(file = clin)

set.seed(seed = 1024)
clin$Disease_Category = sample(
  x = c(
    "Carcinoma",
    "CNS",
    "Germ Cell",
    "Hepatoblastoma",
    "Melanoma",
    "Neuroblastoma",
    "Retinoblastoma",
    "Sarcoma",
    "Wilms Tumor",
    "Other"
  ),
  size = 200,
  replace = TRUE
)

laml = maftools::read.maf(maf = laml.maf, clinicalData = clin)
mycolors = RColorBrewer::brewer.pal(n = 10,name = 'Spectral')
names(mycolors)=c("Carcinoma","CNS","Germ Cell","Hepatoblastoma","Melanoma","Neuroblastoma","Retinoblastoma","Sarcoma","Wilms Tumor","Other")
mycolors = list(Disease_Category = mycolors)

oncoplot(
  maf = laml,
  top = 20,
  clinicalFeatures = 'Disease_Category',
  sortByAnnotation = TRUE,
  annotationColor = mycolors
)
```

If you still get the `is.na` error then it might be the R version that's causing the problem. Also if you don't use the custom colors, does it work fine?

**Comment by AnitaS321** [comment] 2020-12-14 01:45
No, without custom colors the row is blank. I do think it is the R version causing the problem. I've updated R in a different environment, installed maftools, and both functions work properly. I could not get this to work with R3.6. Thank you so much for all your help.

**Closed** 2020-12-15 13:14 UTC
