### ISSUE TITLE
I can't install naftools on Mac Chip Apple M2

### ISSUE THREAD

**Issue by medbenamine** [PoisonAlien/maftools#861] opened 2022-09-05 13:26 UTC
Hi,

I want to install this package “maftools”:
 
if (!require("BiocManager", quietly = TRUE))

    install.packages("BiocManager")

BiocManager::install("maftools")

Then 
 
Library(maftools) 

 
But I get this error : 
 
 

Error: package or namespace load failed for ‘maftools’ in dyn.load(file, DLLpath = DLLpath, ...):

unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':

  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)

  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'

  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'

 
Do you have any idea how can I fix this issue. 
 
 
Thank you

**Comment by ShixiangWang** [comment] 2022-09-06 01:07
Have you tried restart and install again? If do, maybe you can try reinstalling DNAcopy firstly and then install maftools again.

**Comment by medbenamine** [comment] 2022-09-06 12:50
the same thing for "DNAcopy"

> if (!require("BiocManager", quietly = TRUE))
+     
+     install.packages("BiocManager")
> BiocManager::install("DNAcopy", force = TRUE)

Then

> library(DNAcopy)
Error: package or namespace load failed for ‘DNAcopy’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'

**Comment by ShixiangWang** [comment] 2022-09-07 01:44
It seems the issue is related to R instead of maftools. What's the output of installation process? Could you also try installing with `BiocManager::install("DNAcopy", force = TRUE, repos = NULL, type = "source")` and then load again?

**Comment by medbenamine** [comment] 2022-09-07 17:47
> if (!require("BiocManager"))
+     install.packages("BiocManager")
> BiocManager::install("maftools", force = TRUE)


'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for
details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.18), R 4.2.1 (2022-06-23)
Installing package(s) 'maftools'
trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/maftools_2.13.0.tgz'
Content type 'application/x-gzip' length 11563907 bytes (11.0 MB)
==================================================
downloaded 11.0 MB


The downloaded binary packages are in
	/var/folders/5z/t6xchlp911d6r_m_18fjpjncqz8vnk/T//Rtmpg7BUnV/downloaded_packages


 >library(maftools)

Error: package or namespace load failed for ‘maftools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'



> if (!require("BiocManager"))
+     install.packages("BiocManager")
> BiocManager::install("DNAcopy", force = TRUE, repos = NULL, type = "source")

Error: 'repos' argument to 'install()' not allowed

**Comment by ShixiangWang** [comment] 2022-09-09 10:41
Sorry, try `BiocManager::install("DNAcopy", force = TRUE, type = "source")`

**Comment by medbenamine** [comment] 2022-09-09 14:16
BiocManager::install("DNAcopy", force = TRUE, type = "source")

the output is : 
The downloaded source packages are in
	‘/private/var/folders/5z/t6xchlp911d6r_m_18fjpjncqz8vnk/T/Rtmpg7BUnV/downloaded_packages’

library(DNAcopy)

Error: package or namespace load failed for ‘DNAcopy’ in get(method, envir = envir):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/R/DNAcopy.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1

**Comment by ShixiangWang** [comment] 2022-09-09 14:19
Could you restart R (kill R sessions) and run the install command again? If error occurs, please report all logging messages.

**Comment by medbenamine** [comment] 2022-09-10 16:34
It works. Thank you so much for your help.

**Comment by ShixiangWang** [comment] 2022-09-11 13:40
@medbenamine Thanks @PoisonAlien Please close it :)

**Comment by PoisonAlien** [comment] 2022-09-11 14:03
@medbenamine Please accept my apologies for the late replies. Things have been busy and I did not get enough to investigate. I believe Bioconductor/R packages still have some issues with Apple silicon - although rosetta does decent job most of the times. 

@ShixiangWang Thank you so much as always for being responsive :)

**Closed by PoisonAlien** 2022-09-11 14:03 UTC
