### ISSUE TITLE
Plot Signature

### ISSUE THREAD

**Issue by duttaind** [PoisonAlien/maftools#376] opened 2019-08-06 16:05 UTC
Hello,
 Thanks for your responses, I am also working on mutational signature analysis and after running successfully extractSignatures, it results into found 6 signature, But out of these 6 signature, 4 of them points to same signature with different cosine-similarity.

Is there any particular reason why same signature shows up 4 signature with different cosine-similarity.

Thanks

**Comment by PoisonAlien** [comment] 2019-08-07 07:35
Hi,
Since its a de-novo signature analysis, all identified signatures are compared to the list of known signatures from COSMIC. There are two possibilities.

1. Since 4 of the identified signatures are highly similar to the same known signature, its possible you're over-estimating the number of signatures. You can re-run the function with lower (example 3) number of signatures. 
2. Maybe what you have identified are completely new signatures, and the best possible match seems to be the same one in the COSMIC database.

Also how does your elbow plot looks like? You can judge the possible best number of signature from that plot. Its always tricky with the number of signatures.

**Comment by duttaind** [comment] 2019-08-07 15:36
Thanks for your suggestions. Could you please tell how to generate this elbow plot , I mean in extract signature function, it has some heatmap plot generation.

**Comment by duttaind** [comment] 2019-08-07 19:41
Actually I am able to find how to plot this elbow plot from your maftools description, when I started to create it showed this error:
Error: comparison (3) is possible only for atomic and list types

Can you please help, I don't know what it means. Extract Signature was able to run successfully.

**Comment by PoisonAlien** [comment] 2019-08-29 07:03
Hi,
Sorry for the tardy response :|
So if understand correctly, you were able to run `extractSignatures` and generate elbow plot. But the issue is with `plotSignatures`? Could you please post your commands?

**Comment by duttaind** [comment] 2019-08-30 03:33
No, I was not able to create elbow plot, it showed this error:
Error: comparison (3) is possible only for atomic and list types

Please advice.

**Comment by ShixiangWang** [comment] 2019-08-30 04:01
@duttaind You should paste your R commands, otherwise we cannot see why this error happens. It would be best if you can provide an example data.

**Comment by ShixiangWang** [comment] 2019-08-30 04:15
I show you reproduce code, maybe you can follow it.

```
library(maftools)
library(NMF)
library(sigminer)
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)

# Use maftools
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read_maf(maf = laml.maf)
tnm <- trinucleotideMatrix(laml, ref_genome = "BSgenome.Hsapiens.UCSC.hg19", 
                           prefix = "chr", add = TRUE)

# Use sig_estimate from sigminer
sig_estimate(tnm$nmf_matrix, range = 2:5, nrun = 10, verbose = TRUE, pConstant = 0.01)

```

![image](https://user-images.githubusercontent.com/25057508/63992648-6cb90400-cb1f-11e9-9bb6-af32e2c5226f.png)

You can select the best signature number according to this plot. For the meaning of these measures, you can refer to <https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-367>

**Comment by duttaind** [comment] 2019-08-30 21:48
@ShixiangWang , thank you so much for your reply. I was able to create these plots with my data after following your code above. So if I understood minimal on these plots, with "cophenetic of 2 " from your example above, r should be 2. right?  But in my case I don't see any such decrease in cophenetic plot. Please see below.
![factorizationrank](https://user-images.githubusercontent.com/24306160/64052657-680b4480-cb4d-11e9-9f70-c11703dd62d4.png)

The reason I am interested to create these plots on my data because from extract signature module with cosmic, I got 3 enrichment s to same signature with different cosine similarity values and I didn't know  which one to choose. Or do I need to re-run by choosing a specific r value. 

Sorry I can't share any data/details due to institutional restrictions.
Thank you.

**Comment by ShixiangWang** [comment] 2019-08-31 02:07
@duttaind I think you should try more rank range, and give more run to obtain robust result.

Typically, `nrun` should be set to 30-50, you can try 100. `range` you can set it to `2:12` to see the result for more signature number.

```
sig_estimate(tnm$nmf_matrix, range = 2:12, nrun = 100, verbose = TRUE)
```

Based on the plot you showed, I think 4 is the best option. Except for measures shown at the second row should be smaller, other measures should be larger. You can see you will obtain minimal rss when set to 4-5, however, when set to 5, the result generated by random data (shuffling from your actual data) is better than your actual data! Therefore, you should set 4. But I cannot make sure this without result  from a big `nrun`.

**Comment by ShixiangWang** [comment] 2019-08-31 02:14
@duttaind Another thing I want to say is that the signature number obtained from algorithm just help you find a number which you will obtain robust result, this does not mean the signatures based on the number fits the actual biological background/mechanism. You should always explain the result based on your professional knowledge, the measures shown above are helpers, not 
decision makers.

**Comment by duttaind** [comment] 2019-09-04 12:21
@ShixiangWang thank you for suggestions and sorry to reply late.
I did re-run with more r, but I was able to go upto 7 with pConstant = 0.01, otherwise it was showing error.

Here is the plot looks like and you were right r should be 4.

![signature_moreruns](https://user-images.githubusercontent.com/24306160/64254204-ed477e00-ceec-11e9-808f-4bf766cc3df4.png)

**Comment by ShixiangWang** [comment] 2019-11-08 04:18
Should this issue be closed?

**Comment by PoisonAlien** [comment] 2019-11-08 11:02
I like this answer, as it is very descriptive. @duttaind please close the issue if you're happy with the result.

**Closed** 2019-11-10 08:13 UTC
