### ISSUE TITLE
Oncoplot clinical data colours not visible with the github version

### ISSUE THREAD

**Issue by samhitapn** [PoisonAlien/maftools#599] opened 2020-08-26 15:06 UTC
Hello,

I am trying to add clinical features using this Github version (installed using BiocManager::install("PoisonAlien/maftools")). However, the oncoplot returns a legend but not the colour bars on the plot.

Code:
oncoplot(maf,colors = colsVC1,draw_titv = FALSE,
         legendFontSize = 1,fontSize = 0.6,drawColBar = FALSE,clinicalFeatures = Status,showTumorSampleBarcodes = TRUE)

But when I try to do the same thing with the latest BicManager version (installed using BiocManager::install("maftools")), it works perfectly fine.

I tried both maf@clinical.data and adding separately using annotationDat on the Github version, both return the same issue.

Could you help fix this or suggest if I must add anything further?

**Comment by ShixiangWang** [comment] 2020-08-26 15:40
Could you provide a reproducible example?

**Comment by PoisonAlien** [comment] 2020-08-27 06:54
Hi,
I have hard time reproducing the issue? Is it possible to provide a reproducible example? Also what does `colsVC1` looks like?

**Comment by samhitapn** [comment] 2020-08-27 08:33
Here is the code:
colsVC1:
NONSENSE_OR_FRAMESHIFT               MISSENSE                 SPLICE             SYNONYMOUS              MULTI_HIT 
           "#D43F3AB2"            "#EEA236B2"            "#5CB85CB2"            "#46B8DAB2"            "#357EBDB2" 
                   DEL                   OTHERS 
           "#9632B8B2"            "#B8B8B8B2" 

ploidy = c("hotpink","orange","lightpink","grey")
names(ploidy) = c("Diploid","Triploid","Tetraploid","Higher")

chord = c("Red","Blue")
names(chord) = c("HRD","Non-HRD")

lst = c("Red","Blue")
names(lst) = c("HRD","Non-HRD")

colsAnn = list(CHORD = chord,LST = lst,Ploidy = ploidy)

oncoplot(mafExample,colors = colsVC1,draw_titv = FALSE,
         legendFontSize = 1,fontSize = 0.6,drawColBar = FALSE,
         clinicalFeatures = c("CHORD Status","lstStatus","Ploidy Status"),
         showTumorSampleBarcodes = FALSE,
         annotationColor = colsAnn)
-----------------------------------------------
Plot with version 2.0.<>
 ![image](https://user-images.githubusercontent.com/26872279/91416077-2cce4f00-e84f-11ea-9ebe-adbbb3b2ce8b.png)

Plot with version 2.4.1
![image](https://user-images.githubusercontent.com/26872279/91416279-75860800-e84f-11ea-9b9f-86ea377144dd.png)

______________
I wasn't sure how to share the data here: Hope this helps?
[mafExample.pdf](https://github.com/PoisonAlien/maftools/files/5135106/mafExample.pdf)

**Comment by PoisonAlien** [comment] 2020-08-27 09:27
It seems to be the issue with the column names of your clinical features. When you define color codes, make sure it matches to the column names in `maf@clinical.data`. In your cases column names have spaces which might be issue. 

Try the below and see if it works?

```r
colsAnn = list(
  'Ploidy Status' = c('Diploid' = 'blue', 'Triploid' = 'green'),
  'lstStatus' = c('HRD' = 'blue', 'Non-HRD' = 'green'),
  'CHORD Status' = c('Non-HRD' = 'blue', 'HRD' = 'green')
)
```

**Comment by samhitapn** [comment] 2020-08-27 09:49
Oh, sorry I forgot to mention another thing that with the github version, when I add a user-defined colour list using annotationColor = colsAnn, I get the following error:
_Error in if (is.na(col)) { : argument is of length zero_

When I remove the parameter for annotationColor, I get the above figure 2.

I tried now with the redefined colsAnn as per your suggestion, still same error

**Comment by PoisonAlien** [comment] 2020-08-27 10:09
Can you just attach the annotation file (github allows attachments) so that I can reproduce the error?

**Comment by b-niu** [comment] 2020-09-01 06:50
Dear @PoisonAlien  @ShixiangWang ,

In my experience, this has been a slightly long-standing bug.

You can reproduce this by this manner:
```
library(maftools)

#path to TCGA LAML MAF file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') 
#clinical information containing survival information and histology. This is optional
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') 

laml = read.maf(maf = laml.maf, clinicalData = laml.clin)

oncoplot(maf = laml, clinicalFeatures = 'FAB_classification')

```

The result is:
![图片](https://user-images.githubusercontent.com/32410912/91811224-bfad2600-ec61-11ea-934a-673e94ca81e3.png)

In addition, even if you provide an additional parameter "annotationColor", the color will not be displayed.

```
laml@clinical.data$FAB_classification %>% unique()

FAB_ <- unique(na.omit(laml@clinical.data$FAB_classification))
annotation_color <- RColorBrewer::brewer.pal(n = 8, name = 'Set1')[1:length(FAB_)]
names(annotation_color) <- FAB_
annotation_color <- list(FAB_classification = annotation_color)

print(annotation_color)

> print(annotation_color)
$FAB_classification
       M4        M3        M0        M1        M2        M5        M6        M7 
"#E41A1C" "#377EB8" "#4DAF4A" "#984EA3" "#FF7F00" "#FFFF33" "#A65628" "#F781BF" 

oncoplot(maf = laml, clinicalFeatures = 'FAB_classification', annotationColor = annotation_color)
```
![图片](https://user-images.githubusercontent.com/32410912/91811588-51b52e80-ec62-11ea-9e8a-304269714911.png)

The session info is as below:
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /thinker/storage/udata/bing/anaconda3/lib/libopenblasp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.4.10

loaded via a namespace (and not attached):
 [1] compiler_3.6.1     Matrix_1.2-18      tools_3.6.1        RColorBrewer_1.1-2 survival_3.2-3     R.methodsS3_1.8.0  splines_3.6.1      grid_3.6.1        
 [9] data.table_1.12.8  R.utils_2.9.2      packrat_0.5.0      R.oo_1.23.0        lattice_0.20-41   
```

**Comment by PoisonAlien** [comment] 2020-09-01 06:58
That is weird! Both the examples work perfectly on my system with the same version.
I can not think of any reason why this should be happening. Could you try it on another system just to see if you can reproduce it?

**Comment by b-niu** [comment] 2020-09-01 07:41
Yes, of course @PoisonAlien .

Using maftools_ 2.4.05 and R 4.0.2 in Windows platform, it works normally.

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.4.05

loaded via a namespace (and not attached):
 [1] compiler_4.0.2     Matrix_1.2-18      tools_4.0.2        RColorBrewer_1.1-2 survival_3.1-12    tinytex_0.25       splines_4.0.2     
 [8] grid_4.0.2         data.table_1.13.0  xfun_0.16          lattice_0.20-41   
```
![图片](https://user-images.githubusercontent.com/32410912/91820853-ecb10700-ec68-11ea-977d-3213b7f6a0ed.png)


If maftools is updated to 2.4.15, it will work normally too.

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.4.15

loaded via a namespace (and not attached):
 [1] compiler_4.0.2     Matrix_1.2-18      tools_4.0.2        RColorBrewer_1.1-2 survival_3.1-12    R.methodsS3_1.8.0  splines_4.0.2      grid_4.0.2         data.table_1.13.0 
[10] R.utils_2.9.2      R.oo_1.23.0        lattice_0.20-41   
```

![图片](https://user-images.githubusercontent.com/32410912/91821776-719c2080-ec69-11ea-9548-e1d26c6c5b0f.png)


Next, I will test to update maftools on Linux platform to see if it works correctly. Thank you @PoisonAlien ！

**Comment by b-niu** [comment] 2020-09-01 07:47
Ah, it's strange that even if it is updated to 2.4.15 on CentOS platform, it doesn't work properly.

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /thinker/storage/udata/bing/anaconda3/lib/libopenblasp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readxl_1.3.1      data.table_1.12.8 forcats_0.5.0     stringr_1.4.0     dplyr_1.0.0       purrr_0.3.4       readr_1.3.1       tidyr_1.1.0       tibble_3.0.3     
[10] ggplot2_3.3.2     tidyverse_1.3.0   maftools_2.4.15   ngsrtools_0.3.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         cellranger_1.1.0   compiler_3.6.1     pillar_1.4.6       RColorBrewer_1.1-2 dbplyr_1.4.4       tools_3.6.1        packrat_0.5.0     
 [9] lubridate_1.7.9    jsonlite_1.7.0     lifecycle_0.2.0    gtable_0.3.0       lattice_0.20-41    pkgconfig_2.0.3    rlang_0.4.7        reprex_0.3.0      
[17] Matrix_1.2-18      cli_2.0.2          DBI_1.1.0          rstudioapi_0.11    haven_2.3.1        withr_2.2.0        xml2_1.3.2         httr_1.4.1        
[25] fs_1.4.2           hms_0.5.3          generics_0.0.2     vctrs_0.3.2        grid_3.6.1         tidyselect_1.1.0   glue_1.4.1         R6_2.4.1          
[33] fansi_0.4.1        survival_3.2-3     modelr_0.1.8       blob_1.2.1         magrittr_1.5       backports_1.1.8    scales_1.1.1       ellipsis_0.3.1    
[41] splines_3.6.1      rvest_0.3.5        assertthat_0.2.1   colorspace_1.4-1   stringi_1.4.6      munsell_0.5.0      broom_0.7.0        crayon_1.3.4     
```

**Comment by PoisonAlien** [comment] 2020-09-01 07:59
Hmm.. Very strange. I will try to run it on CentOS and see if I can reproduce your results. 
Hi @samhitapn ,  Are you also using CentOS systems?

**Comment by samhitapn** [comment] 2020-09-03 14:53
Hi,
Sorry I got caught up with some work. Indeed the error is as explained by @b-niu.
@PoisonAlien, no, I am using R 3.6.0 on Windows.

**Comment by b-niu** [comment] 2020-09-04 09:26
It sounds like a problem of R3.6. 
I will upgrade R to 4.0 and test agian on CentOS.

**Comment by b-niu** [comment] 2020-09-07 05:07
I tested maftools on Debian OS. Using R4.0.2, oncoplot() works normally.

It seems that the problem lies in the incompatibility between the oncolot() function and R3.6. But the details remain unknown...

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS/LAPACK: /opt/conda/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0     stringr_1.4.0     dplyr_1.0.2       purrr_0.3.4       readr_1.3.1       tidyr_1.1.2      
 [7] tibble_3.0.3      ggplot2_3.3.2     tidyverse_1.3.0   readxl_1.3.1      data.table_1.12.8 ngsrtools_0.3.1  
[13] maftools_2.4.15  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5          BiocManager_1.30.10 cellranger_1.1.0    pillar_1.4.6        compiler_4.0.2      RColorBrewer_1.1-2 
 [7] dbplyr_1.4.4        tools_4.0.2         lubridate_1.7.9     jsonlite_1.7.0      lifecycle_0.2.0     gtable_0.3.0       
[13] lattice_0.20-41     pkgconfig_2.0.3     rlang_0.4.7         reprex_0.3.0        Matrix_1.2-18       cli_2.0.2          
[19] DBI_1.1.0           rstudioapi_0.11     haven_2.3.1         withr_2.2.0         xml2_1.3.2          httr_1.4.2         
[25] fs_1.5.0            hms_0.5.3           generics_0.0.2      vctrs_0.3.4         grid_4.0.2          tidyselect_1.1.0   
[31] glue_1.4.2          R6_2.4.1            fansi_0.4.1         survival_3.2-3      modelr_0.1.8        blob_1.2.1         
[37] magrittr_1.5        backports_1.1.9     scales_1.1.1        ellipsis_0.3.1      splines_4.0.2       rvest_0.3.6        
[43] assertthat_0.2.1    colorspace_1.4-1    stringi_1.4.6       munsell_0.5.0       broom_0.7.0         crayon_1.3.4 
```

**Comment by PoisonAlien** [comment] 2020-09-07 07:12
Thank you so much for testing!  This is surprising. 
I had never encountered this while the package was running on 3.6. I will have to dig bit deeper to see what is exactly causing it.

**Comment by justannwska** [comment] 2020-10-09 09:49
I have similar problem using macOS, and R 3.6.3.

Has anyone figured out what is wrong? And how to circumvent it?

<img width="599" alt="Untitled 17" src="https://user-images.githubusercontent.com/58563895/95569140-7486ef80-0a25-11eb-8ff4-a09e1e7d7e09.png">

**Comment by PoisonAlien** [comment] 2020-10-09 13:33
Hey Justy,
Thanks for reminding. After struggling for hours I figured it out. In R < 4.0 by default `stringAsFactors = TRUE` which messed up character conversion. It should be working now..
Could you please test it again and let me know if it works? You will have to install from GitHub for the patched version.

**Comment by cjhong** [comment] 2020-10-09 14:45
> Hey Justy,
> Thanks for reminding. After struggling for hours I figured it out. In R < 4.0 by default `stringAsFactors = TRUE` which messed up character conversion. It should be working now..
> Could you please test it again and let me know if it works? You will have to install from GitHub for the patched version.

Thank you, Now, it works on R3.4.3/CentOS.

**Comment by PoisonAlien** [comment] 2020-10-09 16:31
@cjhong 
Thanks for testing. I am closing the issue. Please feel free to reopen if necessary.

**Closed by PoisonAlien** 2020-10-09 16:31 UTC

**Comment by justannwska** [comment] 2020-10-10 20:04
Thanks so much! It's working:)
