### ISSUE TITLE
Reference fasta is not working & "Zero mutations to analyze!"

### ISSUE THREAD

**Issue by prxrsp** [PoisonAlien/maftools#75] opened 2017-10-27 03:35 UTC
Dear PoisonAlien, 

Thank you for this amazing package!

I am very new to programming, so please forgive me if this is a stupid question. 
I understand I have to download my own hg19 fasta file, which should include all chromosomes. Ensembl and UCSC will only let you download separate fasta files for each chromosome. I did manage to find a single file from 1000genomes that presumably contains sequence from all chromosomes, however when I tried running it, I got this error message: 

```
reading human_b36_male.fa.gz (this might take few minutes)..
Error in trinucleotideMatrix(maf = my.maf, ref_genome = "human_b36_male.fa.gz",  : 
  Zero mutations to analyze! Maybe add or remove prefix?
In addition: Warning message:
In trinucleotideMatrix(maf = my.maf, ref_genome = "human_b36_male.fa.gz",  :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 303 single nucleotide variants from missing chromosomes chr7, chr8, chr4, chr2, chr1, chr5, chr6, chr14, chrX, chr9, chr17, chr16, chr18, chr12, chr11, chr3, chr19, chr20, chr22, chr15, chr21, chr13, chr10
```
Looking for an answer on this page, I bumped into a similar issue, where you mentioned that chromosome naming could vary (for example "chr1" vs. "1"), so I tried skipping prefix argument, however I got the same error message. 

That being said, downloading the right reference genome is only half of the problem, since apparently it did not find any mutations to analyze either. Other maftools functions have worked OK so far and there are mutations to be analyzed...

I would really appreciate your help!

**Comment by PoisonAlien** [comment] 2017-10-27 03:47
Hi,
It appears that chromosome names in fasta file has `chr` prefix whereas maf file doesn't have this. 
Maybe try below and see if it works ?

```
trinucleotideMatrix(maf = my.maf, ref_genome = "human_b36_male.fa.gz", prefix = "chr", add = TRUE)
```

**Comment by prxrsp** [comment] 2017-10-27 04:46
Thank you for getting back to me!

I tried it, but it did not work. 

```
> my.maf.tnm = trinucleotideMatrix(maf = my.maf , ref_genome = "human_b36_male.fa.gz", prefix = "chr", add = TRUE)
reading human_b36_male.fa.gz (this might take few minutes)..
Error in trinucleotideMatrix(maf = my.maf, ref_genome = "human_b36_male.fa.gz",  : 
  Zero mutations to analyze! Maybe add or remove prefix?
In addition: Warning message:
In trinucleotideMatrix(maf = my.maf, ref_genome = "human_b36_male.fa.gz",  :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 303 single nucleotide variants from missing chromosomes chr7, chr8, chr4, chr2, chr1, chr5, chr6, chr14, chrX, chr9, chr17, chr16, chr18, chr12, chr11, chr3, chr19, chr20, chr22, chr15, chr21, chr13, chr10
```

**Comment by PoisonAlien** [comment] 2017-10-27 05:08
Oh ! That is strange. 
Can you run the below command and post your output ?

```r
subsetMaf(maf = my.maf, fields = "Tumor_Sample_Barcode", query = "Variant_Type == 'SNP'")[,.N,.(Chromosome)]
```

**Comment by prxrsp** [comment] 2017-10-27 13:19
`subsetMaf(maf = my.maf, fields = "Tumor_Sample_Barcode", query = "Variant_Type == 'SNP'")[,.N,.(Chromosome)]
    Chromosome  N
 1:          7 14
 2:          8 15
 3:          4 20
 4:          2 22
 5:          1 32
 6:          5 26
 7:          6 17
 8:         14 13
 9:          X 11
10:          9 15
11:         17 11
12:         16  8
13:         18  4
14:         12 12
15:         11 11
16:          3 26
17:         19 16
18:         20  8
19:         22  7
20:         15  6
21:         21  4
22:         13  1
23:         10  4
    Chromosome  N`

Thanks so much for the help!

**Comment by prxrsp** [comment] 2017-10-27 13:47
Hi again, 

I tried changing chromosome names to "chr1" etc. and ran this: 
```
trinucleotideMatrix(maf = my.maf, ref_genome = 'human_b36_male.fa.gz', 
                                 ignoreChr = 'chr23', useSyn = TRUE)
```

I got the same error message. Is there any chance my Fasta file is the problem?

I am downloading another file, human_g1k_v37.fasta.gz, and I will update this thread with my results.

Thank you so much!

**Comment by prxrsp** [comment] 2017-10-30 13:53
Hello, 

I used human_g1k_v37.fasta.gz as ref_genome, but it did not work. I get the same error message. 

```
> my.maf.tnm = trinucleotideMatrix(maf = my.maf, ref_genome = 'human_g1k_v37.fasta.gz', 
+                                  prefix = 'chr', add = TRUE)
reading human_g1k_v37.fasta.gz (this might take few minutes)..
Error in trinucleotideMatrix(maf = my.maf, ref_genome = "human_g1k_v37.fasta.gz",  : 
  Zero mutations to analyze! Maybe add or remove prefix?
In addition: Warning message:
In trinucleotideMatrix(maf = my.maf, ref_genome = "human_g1k_v37.fasta.gz",  :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 303 single nucleotide variants from missing chromosomes chr7, chr8, chr4, chr2, chr1, chr5, chr6, chr14, chrX, chr9, chr17, chr16, chr18, chr12, chr11, chr3, chr19, chr20, chr22, chr15, chr21, chr13, chr10

```

**Comment by PoisonAlien** [comment] 2017-10-31 02:25
Hi,
This is weird. Even I am not sure what;s gong on. Do you think you can share your maf file ? You can mail me if you don't want to attach here (anandmt3@gmail.com)

**Comment by ckandoth** [comment] 2017-11-23 00:29
Same issue. Here's some info to help debug.
- Compiled `R-3.4.1` from source on CentOS 6.
- Installed latest maftools using `devtools::install_github( "PoisonAlien/maftools" )`.
- Reference genome is [Ensembl's GRCh37 FASTA](ftp://ftp.ensembl.org:/pub/release-75/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz) plus some decoy sequences i.e. `1, 2, 3, ..., X, Y, MT, GL000207.1, ..., GL000192.1, NC_007605, hs37d5`).
- The MAF file uses exactly the same chromosome names as the FASTA above.
- Running `trinucleotideMatrix` on the MAF using the GRCh37 fasta fails like this:

```bash
> mut.tnm = trinucleotideMatrix( maf=mut, ref_genome='/ifs/depot/assemblies/H.sapiens/b37/b37.fasta' )
reading /ifs/depot/assemblies/H.sapiens/b37/b37.fasta (this might take few minutes)..
Error in trinucleotideMatrix(maf = mut, ref_genome = "/ifs/depot/assemblies/H.sapiens/b37/b37.fasta") :
  Zero mutations to analyze! Maybe add or remove prefix?
In addition: Warning message:
In trinucleotideMatrix(maf = mut, ref_genome = "/ifs/depot/assemblies/H.sapiens/b37/b37.fasta") :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 6604 single nucleotide variants from missing chromosomes 1, 3, 5, 6, 8, 10, 15, 17, GL000209.1, X, 11, 12, 16, 7, 18, 19, GL000212.1, MT, 14, 22, 2, 9, 13, GL000218.1, 4, Y, 20, 21, GL000219.1, GL000242.1, GL000205.1, GL000213.1, GL000192.1
```
- It partially works if I use UCSC's hg19 FASTA, and prefix the MAF chroms with `chr`, but then `MT` and the unaligned contigs don't match up:

```bash
> mut.tnm = trinucleotideMatrix( maf=mut, ref_genome='/ifs/depot/assemblies/H.sapiens/hg19/hg19.fasta', prefix='chr', add=TRUE )
reading /ifs/depot/assemblies/H.sapiens/hg19/hg19.fasta (this might take few minutes)..
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background C>T estimation..
Estimating APOBEC enrichment scores..
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 17.833% of samples (APOBEC enrichment score > 2 ; 79 of 443 samples)
Creating mutation matrix..
matrix of dimension 443x96
Warning message:
In trinucleotideMatrix(maf = mut, ref_genome = "/ifs/depot/assemblies/H.sapiens/hg19/hg19.fasta",  :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 859 single nucleotide variants from missing chromosomes chrGL000209.1, chrGL000212.1, chrMT, chrGL000218.1, chrGL000219.1, chrGL000242.1, chrGL000205.1, chrGL000213.1, chrGL000192.1
```

**Comment by PoisonAlien** [comment] 2017-12-08 05:38
Hi,
Please accept my apologies for late reply. 

I have tried several maf files with both ucsc and ensemble ref genomes and it seems to be working fine. Even @prxrsp mailed me his maf file and it worked fine with both the fasta files. Do you still have this issue ? Can you post your sessionInfo ?

Regarding mitochondrial and other contigs, I am not sure how to tackle this. Only way seems to be changing chromosome names in maf files to the ones in fasta file or ignore such chromosomes with `ignoreChr` argument.

**Comment by ckandoth** [comment] 2017-12-08 07:33
No worries. Glad to help debug. Here are some steps to reproduce the issue using publicly available files:
```
# Download a TCGA MAF, and a reference FASTA compatible with it:
curl -LO https://raw.githubusercontent.com/mskcc/vcf2maf/v1.6.14/data/tcga_laml.maf
curl -LO ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz

# Unzip the FASTA (since Rsamtools won't support fa.gz), and index it using samtools 1.6:
gunzip Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
samtools faidx Homo_sapiens.GRCh37.75.dna.primary_assembly.fa

# Start R interactively with maftools installed and do the following:
> library(maftools)
> mut <- read.maf( maf="tcga_laml.maf" )
> mut.tnm <- trinucleotideMatrix( maf=mut, ref_genome='Homo_sapiens.GRCh37.75.dna.primary_assembly.fa' )

reading Homo_sapiens.GRCh37.75.dna.primary_assembly.fa (this might take few minutes)..
Error in trinucleotideMatrix(maf = mut, ref_genome = "Homo_sapiens.GRCh37.75.dna.primary_assembly.fa") :
  Zero mutations to analyze! Maybe add or remove prefix?
In addition: Warning message:
In trinucleotideMatrix(maf = mut, ref_genome = "Homo_sapiens.GRCh37.75.dna.primary_assembly.fa") :
  Chromosome names in MAF must match chromosome names in reference fasta. Ignorinig 2275 single nucleotide variants from missing chromosomes 1, 2, 10, 12, 20, 3, 4, 6, 7, 11, 15, X, 16, 19, 9, 13, 18, 21, 5, 14, 8, 17, 22
```
It looks like [VariantAnnotation::getSeq in this code block](https://github.com/PoisonAlien/maftools/blob/master/R/TrinucleotideMatrix.R#L74-L83) is incorrectly parsing the chromosome names from the FASTA. For example:
```
> ref = Rsamtools::FaFile(file = "Homo_sapiens.GRCh37.75.dna.primary_assembly.fa")
> head(VariantAnnotation::seqlevels(ref))

[1] "1"  "10" "11" "12" "13" "14"

> ref = VariantAnnotation::getSeq(x = ref)
> head(VariantAnnotation::seqlevels(ref))

[1] "1 dna:chromosome chromosome:GRCh37:1:1:249250621:1 REF"
[2] "10 dna:chromosome chromosome:GRCh37:10:1:135534747:1 REF"
[3] "11 dna:chromosome chromosome:GRCh37:11:1:135006516:1 REF"
[4] "12 dna:chromosome chromosome:GRCh37:12:1:133851895:1 REF"
[5] "13 dna:chromosome chromosome:GRCh37:13:1:115169878:1 REF"
[6] "14 dna:chromosome chromosome:GRCh37:14:1:107349540:1 REF"
```
Here's my sessionInfo() anyway:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /opt/common/CentOS_6-dev/R/R-3.4.1/lib64/R/lib/libRblas.so
LAPACK: /opt/common/CentOS_6-dev/R/R-3.4.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] Biostrings_2.46.0     XVector_0.18.0        IRanges_2.12.0
 [4] S4Vectors_0.16.0      BiocInstaller_1.28.0  maftools_1.4.05
 [7] synchronicity_1.1.9.1 bigmemory_4.5.31      bigmemory.sri_0.1.3
[10] Biobase_2.38.0        BiocGenerics_0.24.0

loaded via a namespace (and not attached):
 [1] RMySQL_0.10.13             bit64_0.9-7
 [3] splines_3.4.1              foreach_1.4.3
 [5] assertthat_0.2.0           blob_1.1.0
 [7] BSgenome_1.46.0            GenomeInfoDbData_0.99.1
 [9] Rsamtools_1.30.0           slam_0.1-40
[11] progress_1.1.2             ggrepel_0.7.0
[13] RSQLite_2.0                lattice_0.20-35
[15] digest_0.6.12              GenomicRanges_1.30.0
[17] RColorBrewer_1.1-2         colorspace_1.3-2
[19] cowplot_0.9.1              Matrix_1.2-12
[21] plyr_1.8.4                 XML_3.98-1.9
[23] GetoptLong_0.1.6           biomaRt_2.34.0
[25] zlibbioc_1.24.0            xtable_1.8-2
[27] scales_0.5.0               BiocParallel_1.12.0
[29] tibble_1.3.4               pkgmaker_0.22
[31] ggplot2_2.2.1              SummarizedExperiment_1.8.0
[33] GenomicFeatures_1.30.0     lazyeval_0.2.1
[35] mclust_5.4                 survival_2.41-3
[37] magrittr_1.5               memoise_1.1.0
[39] doParallel_1.0.11          changepoint_2.2.2
[41] NMF_0.20.6                 prettyunits_1.0.2
[43] tools_3.4.1                registry_0.3
[45] data.table_1.10.4-3        GlobalOptions_0.0.12
[47] matrixStats_0.52.2         gridBase_0.4-7
[49] ComplexHeatmap_1.17.1      stringr_1.2.0
[51] munsell_0.4.3              cluster_2.0.6
[53] rngtools_1.2.4             DelayedArray_0.4.1
[55] AnnotationDbi_1.40.0       compiler_3.4.1
[57] GenomeInfoDb_1.14.0        rlang_0.1.4
[59] grid_3.4.1                 RCurl_1.95-4.8
[61] iterators_1.0.8            VariantAnnotation_1.24.2
[63] rjson_0.2.15               circlize_0.4.2
[65] bitops_1.0-6               gtable_0.2.0
[67] codetools_0.2-15           DBI_0.7
[69] R6_2.2.2                   reshape2_1.4.2
[71] gridExtra_2.3              zoo_1.8-0
[73] GenomicAlignments_1.14.1   rtracklayer_1.38.0
[75] bit_1.1-12                 shape_1.4.3
[77] stringi_1.1.6              Rcpp_0.12.14
[79] wordcloud_2.5
```

**Comment by PoisonAlien** [comment] 2017-12-08 08:40
Ah !!! Excellent catch. That seems to be the issue. It appears that contig names should be stripped after the first space (similar to what samtools index does) 
I will fix it soon ! :)

**Comment by PoisonAlien** [comment] 2017-12-11 08:28
Hi,

I have pushed a commit which should fix the issue. Can you try it out and see?

**Comment by ckandoth** [comment] 2017-12-13 00:51
Nice. I used `devtools::install_github` to install the master branch, and the following works great:
```
> mut.tnm = trinucleotideMatrix( maf=mut, ref_genome='/ifs/depot/assemblies/H.sapiens/b37/b37.fasta' )
reading /ifs/depot/assemblies/H.sapiens/b37/b37.fasta (this might take few minutes)..
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background C>T estimation..
Estimating APOBEC enrichment scores..
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 17.833% of samples (APOBEC enrichment score > 2 ; 79 of 443 samples)
Creating mutation matrix..
matrix of dimension 443x96
```

**Comment by PoisonAlien** [comment] 2017-12-13 07:12
Hi,
Thanks again for the help. I am closing this issue.

**Closed by PoisonAlien** 2017-12-13 07:12 UTC
