### ISSUE TITLE
Annotation legend order is not correct

### ISSUE THREAD

**Issue by pkhoueiry** [PoisonAlien/maftools#541] opened 2020-06-02 16:58 UTC
**Describe the issue**
In the newest maftools versions (Bioconductor version 2.4 and Github v2.4.05), the annotations are shuffled. 
For instance, the annotation for resection is under time2Recurrence

<img width="940" alt="Screen Shot 2020-06-02 at 19 53 28" src="https://user-images.githubusercontent.com/5323250/83547353-c1543a00-a50a-11ea-9d5a-b12fb771affa.png">

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
oncoplot(maf = maf, removeNonMutated = TRUE, colors = col, showTumorSampleBarcodes = FALSE,  clinicalFeatures = c("Gender", "Multifocal", "Age", "Resection", "Time2Death", "Time2Recurrence"), top = 50, annotationColor = annotationColor, legendFontSize = 1, fontSize = 0.5, anno_height = 1.5)
```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RColorBrewer_1.1-2 reshape2_1.4.4     maftools_2.4.05   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        rstudioapi_0.11     magrittr_1.5        splines_4.0.0       lattice_0.20-41     R6_2.4.1           
 [7] fansi_0.4.1         stringr_1.4.0       plyr_1.8.6          tools_4.0.0         pkgbuild_1.0.8      grid_4.0.0         
[13] data.table_1.12.8   cli_2.0.2           withr_2.2.0         remotes_2.1.1       rprojroot_1.3-2     survival_3.1-12    
[19] yaml_2.2.1          assertthat_0.2.1    crayon_1.3.4        processx_3.4.2      Matrix_1.2-18       BiocManager_1.30.10
[25] callr_3.4.3         ps_1.3.3            curl_4.3            glue_1.4.1          stringi_1.4.6       compiler_4.0.0     
[31] backports_1.1.7     prettyunits_1.1.1  
```

**Comment by PoisonAlien** [comment] 2020-06-04 14:55
Hi,
Are you sure about the swapping? I am trying to reproduce the issue with several TCGA datasets but it seems to be in proper order. 
Can you double check your clinical data if everything is in proper order and columns are not wrongly labelled?

**Comment by pkhoueiry** [comment] 2020-06-05 07:48
I think so. I believe the match between the names in the list `annotationColor` and `clinicalFeatures` is buggy.

**Comment by PoisonAlien** [comment] 2020-06-06 09:04
Thanks for reporting. I was able to reproduce it. 
I have pushed a fix, please try it out (from GitHub) and let me know if this helps.

**Closed** 2020-06-14 08:24 UTC
