### ISSUE TITLE
`estimateSignatures` take too long time 

### ISSUE THREAD

**Issue by likelet** [PoisonAlien/maftools#433] opened 2019-12-03 09:09 UTC
I have a cohort of about 800 patients and gonna use `estimateSignatures` to get signatures for clinical correlation analysis. it took about 2 days and it was still running without an estimated end time. I suggest that it's a good option to add a progress text in the `estimateSignatures` function.

**Comment by ShixiangWang** [comment] 2019-12-03 09:19
It indeed takes a lot of time. You can test the rank range with small runs and then use a short rank range.

**Comment by PoisonAlien** [comment] 2019-12-03 09:27
Hi,
I am sorry that the function is taking such long run-times. `estimateSignatures` function runs [nmfEstimateRank](https://github.com/PoisonAlien/maftools/blob/master/R/estimateSignatures.R#L52) from `nmf ` r package. This function depends on maximum number of signatures to try. In your I guess you had the larger value for `nTry`. I do agree that this is computationally expensive, but I am not sure if I can add a progress bar since the underlying code doesnt use any loops. I will try to figure out an alternative option.

**Comment by PoisonAlien** [comment] 2019-12-04 16:06
Hi,
Thanks again for the issue. I have made some changes the function bit more verbose and flexible. 
* I have added `nMin` argument by which you can specify minimum number of signature to try (and not starting with 1 as a default).
* `nrun` the number of run to perform for each value in range. Default is ten, but now you can lower it to decrease the run time.
* `verbose` set it to `TRUE` (default) and it will print for every value in range its currently working on.

If you were to try, please do let me know if this helps.

**Comment by likelet** [comment] 2019-12-05 07:33
well, thanks for the reply. I will have a try and give feedback  once it is done

**Comment by likelet** [comment] 2019-12-09 03:49
it still running at present, seems it stuck somewhere
![image](https://user-images.githubusercontent.com/3021506/70405919-d0858e00-1a79-11ea-8cfa-7a15e5cb0546.png)
all tasks are suspended with no warning. so any suggestion?

**Comment by ShixiangWang** [comment] 2019-12-09 06:22
This is time-consuming because you have 800 samples, you have to wait. Do you enable parallel computation?

**Comment by likelet** [comment] 2019-12-09 06:24
Yes, I run it in parallel with more than 20 cores

**Comment by PoisonAlien** [comment] 2019-12-09 08:44
Hmm.. I can understand that its a time consuming process but four days is a bit too much. I will try to run this on tcga brca (N > 1000) cohort to see if I can reproduce this.

**Comment by PoisonAlien** [comment] 2019-12-09 13:20
Okay. tested on tcga brca cohort and it seem to be quite fast. It took under 3 minutes for me to finish the job. However, increasing `nrun = 10` increased the run time but it never exceeded 5 minutes. 

```r
> brca = TCGAmutations::tcga_load(study = "BRCA")
> brca
An object of class  MAF 
                        ID summary   Mean Median
 1:             NCBI_Build      NA     NA     NA
 2:                 Center      NA     NA     NA
 3:                Samples    1020     NA     NA
 4:                 nGenes   16686     NA     NA
 5:        Frame_Shift_Del    9324  9.141    1.0
 6:        Frame_Shift_Ins     961  0.942    0.5
 7:           In_Frame_Del     683  0.670    0.0
 8:           In_Frame_Ins      50  0.049    0.0
 9:      Missense_Mutation   69328 67.969   35.0
10:      Nonsense_Mutation    5890  5.775    3.0
11:       Nonstop_Mutation      90  0.088    0.0
12:            Splice_Site    2084  2.043    1.0
13: Translation_Start_Site      93  0.091    0.0
14:                  total   88503 86.768   41.0

>brca_tnm = maftools::trinucleotideMatrix(maf = brca, ref_genome = "BSgenome.Hsapiens.UCSC.hg19", prefix = "chr")

#estimate signatures with nrun=2
> brca_sig_est = maftools::estimateSignatures(mat = brca_tnm, nMin = 2, nTry = 8, nrun = 2, parallel = '6', verbose = TRUE)
-Running NMF for 8 ranks
Compute NMF rank= 2  ... + measures ... OK
Compute NMF rank= 3  ... + measures ... OK
Compute NMF rank= 4  ... + measures ... OK
Compute NMF rank= 5  ... + measures ... OK
Compute NMF rank= 6  ... + measures ... OK
Compute NMF rank= 7  ... + measures ... OK
Compute NMF rank= 8  ... + measures ... OK
-Finished in 00:02:11 elapsed (12.8s cpu) 

#with nrun=4
> brca_sig_est2 = maftools::estimateSignatures(mat = brca_tnm, nMin = 3, nTry = 8, nrun = 4, parallel = '6', verbose = TRUE)
-Running NMF for 8 ranks
Compute NMF rank= 3  ... + measures ... OK
Compute NMF rank= 4  ... + measures ... OK
Compute NMF rank= 5  ... + measures ... OK
Compute NMF rank= 6  ... + measures ... OK
Compute NMF rank= 7  ... + measures ... OK
Compute NMF rank= 8  ... + measures ... OK
-Finished in 00:02:22 elapsed (10.3s cpu) 

#with nrun=10
> brca_sig_est3 = maftools::estimateSignatures(mat = brca_tnm, nMin = 2, nTry = 8, nrun = 10, parallel = '6', verbose = TRUE)
-Running NMF for 8 ranks
Compute NMF rank= 2  ... + measures ... OK
Compute NMF rank= 3  ... + measures ... OK
Compute NMF rank= 4  ... + measures ... OK
Compute NMF rank= 5  ... + measures ... OK
Compute NMF rank= 6  ... + measures ... OK
Compute NMF rank= 7  ... + measures ... OK
Compute NMF rank= 8  ... + measures ... OK
-Finished in 00:04:19 elapsed (12.4s cpu)
```

I am running this on Ubuntu system with 64GB RAM and 8 threads. This is my `sessionInfo`
```r
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Pop!_OS 18.04 LTS           
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2019-12-09                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version date       lib source                               
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                       
 bibtex         0.4.2   2017-06-30 [1] CRAN (R 3.6.0)                       
 Biobase      * 2.46.0  2019-10-29 [1] Bioconductor                         
 BiocGenerics * 0.32.0  2019-10-29 [1] Bioconductor                         
 cli            2.0.0   2019-12-09 [1] CRAN (R 3.6.0)                       
 cluster      * 2.1.0   2019-06-19 [1] CRAN (R 3.6.0)                       
 codetools      0.2-16  2018-12-24 [1] CRAN (R 3.6.0)                       
 colorspace     1.4-1   2019-03-18 [1] CRAN (R 3.6.0)                       
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                       
 data.table     1.12.6  2019-10-18 [1] CRAN (R 3.6.0)                       
 digest         0.6.23  2019-11-23 [1] CRAN (R 3.6.0)                       
 doParallel   * 1.0.15  2019-08-02 [1] CRAN (R 3.6.0)                       
 dplyr          0.8.3   2019-07-04 [1] CRAN (R 3.6.0)                       
 fansi          0.4.0   2018-10-05 [1] CRAN (R 3.6.0)                       
 foreach      * 1.4.7   2019-07-27 [1] CRAN (R 3.6.0)                       
 ggplot2        3.2.1   2019-08-10 [1] CRAN (R 3.6.0)                       
 glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)                       
 gridBase       0.4-7   2014-02-24 [1] CRAN (R 3.6.0)                       
 gtable         0.3.0   2019-03-25 [1] CRAN (R 3.6.0)                       
 iterators    * 1.0.12  2019-07-26 [1] CRAN (R 3.6.0)                       
 lattice        0.20-38 2018-11-04 [1] CRAN (R 3.6.0)                       
 lazyeval       0.2.2   2019-03-15 [1] CRAN (R 3.6.0)                       
 lifecycle      0.1.0   2019-08-01 [1] CRAN (R 3.6.0)                       
 maftools     * 2.2.10  2019-12-09 [1] Github (poisonalien/maftools@ababa53)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)                       
 Matrix         1.2-18  2019-11-27 [1] CRAN (R 3.6.0)                       
 munsell        0.5.0   2018-06-12 [1] CRAN (R 3.6.0)                       
 NMF          * 0.21.0  2018-03-06 [1] CRAN (R 3.6.0)                       
 pillar         1.4.2   2019-06-29 [1] CRAN (R 3.6.0)                       
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 3.6.0)                       
 pkgmaker     * 0.27    2018-05-25 [1] CRAN (R 3.6.0)                       
 plyr           1.8.4   2016-06-08 [1] CRAN (R 3.6.0)                       
 purrr          0.3.3   2019-10-18 [1] CRAN (R 3.6.0)                       
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.0)                       
 RColorBrewer   1.1-2   2014-12-07 [1] CRAN (R 3.6.0)                       
 Rcpp           1.0.3   2019-11-08 [1] CRAN (R 3.6.0)                       
 registry     * 0.5-1   2019-03-05 [1] CRAN (R 3.6.0)                       
 reshape2       1.4.3   2017-12-11 [1] CRAN (R 3.6.0)                       
 rlang          0.4.2   2019-11-23 [1] CRAN (R 3.6.0)                       
 rngtools     * 1.4     2019-07-01 [1] CRAN (R 3.6.0)                       
 rstudioapi     0.10    2019-03-19 [1] CRAN (R 3.6.0)                       
 scales         1.1.0   2019-11-18 [1] CRAN (R 3.6.0)                       
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                       
 stringi        1.4.3   2019-03-12 [1] CRAN (R 3.6.0)                       
 stringr        1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                       
 survival       3.1-8   2019-12-03 [1] CRAN (R 3.6.0)                       
 tibble         2.1.3   2019-06-06 [1] CRAN (R 3.6.0)                       
 tidyselect     0.2.5   2018-10-11 [1] CRAN (R 3.6.0)                       
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                       
 wordcloud      2.6     2018-08-24 [1] CRAN (R 3.6.0)                       
 xtable         1.8-4   2019-04-21 [1] CRAN (R 3.6.0)                       

[1] /home/anand/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```

**Comment by likelet** [comment] 2019-12-10 08:55
hi PoisonAlien. 
it seems stuck for an unknown reason in my side, I will send the object file by email.
Thanks for your help!

**Comment by PoisonAlien** [comment] 2019-12-10 13:34
Hi @likelet ,

Thank you for sharing the data. I ran `estimateSignatures` on your tnm and it finished in under 8 mins with 6 threads.

```r
> bestfit = maftools::estimateSignatures(mat = sysucc.nonHyperMut.nmf, nMin = 2, nTry = 12, nrun = 10, parallel = '6')
-Running NMF for 12 ranks
Compute NMF rank= 2  ... + measures ... OK
Compute NMF rank= 3  ... + measures ... OK
Compute NMF rank= 4  ... + measures ... OK
Compute NMF rank= 5  ... + measures ... OK
Compute NMF rank= 6  ... + measures ... OK
Compute NMF rank= 7  ... + measures ... OK
Compute NMF rank= 8  ... + measures ... OK
Compute NMF rank= 9  ... + measures ... OK
Compute NMF rank= 10  ... + measures ... OK
Compute NMF rank= 11  ... + measures ... OK
Compute NMF rank= 12  ... + measures ... OK
-Finished in 00:07:44 elapsed (18.7s cpu)
```
I am having hard time to figure out the issue. 

1. Can you check your `nmf` package version? I am using `0.21.0`.  Install `nmf` package from [GitHub](https://github.com/renozao/NMF) if necessary since it seems to be not updated on CRAN.

2. Also are you by any chance using `macOS`? 

3. Make sure none of the packages built with `SummarizedExperiment` are loaded. NMF has some [issues](https://github.com/renozao/NMF/issues/85#issuecomment-475985902) with it.

Please let me know if any of the above things helps.

**Comment by likelet** [comment] 2019-12-11 02:56
hi @PoisonAlien ,
thanks for your testing, here is my sessioninfo, I have only `maftools` and `NMF` loaded in the env. 
and the version of `NMF` is `0.21.0`. BTW: could you send the `bestfit` object to me and I will have a look at the result firstly?
```R
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS: /usr/lib/R/lib/libRblas.so
LAPACK: /usr/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] NMF_0.21.0           synchronicity_1.3.5  bigmemory_4.5.33    
 [4] Biobase_2.40.0       BiocGenerics_0.26.0  cluster_2.0.7-1     
 [7] rngtools_1.3.1       pkgmaker_0.27        registry_0.5        
[10] maftools_2.2.10      RevoUtils_11.0.3     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2          plyr_1.8.4          compiler_3.5.3     
 [4] pillar_1.4.2        RColorBrewer_1.1-2  iterators_1.0.11   
 [7] tools_3.5.3         uuid_0.1-2          digest_0.6.20      
[10] gridBase_0.4-7      tibble_2.1.3        gtable_0.3.0       
[13] lattice_0.20-38     pkgconfig_2.0.2     rlang_0.4.0        
[16] Matrix_1.2-15       bibtex_0.4.2        foreach_1.5.1      
[19] dplyr_0.8.0.1       withr_2.1.2         stringr_1.4.0      
[22] tidyselect_0.2.5    grid_3.5.3          wordcloud_2.6      
[25] glue_1.3.1          data.table_1.12.6   R6_2.4.0           
[28] bigmemory.sri_0.1.3 survival_2.42-6     reshape2_1.4.3     
[31] purrr_0.3.2         ggplot2_3.2.1.9000  magrittr_1.5       
[34] scales_1.0.0        codetools_0.2-16    splines_3.5.3      
[37] assertthat_0.2.1    xtable_1.8-2        colorspace_1.3-2   
[40] stringi_1.2.4       lazyeval_0.2.2      doParallel_1.0.14  
[43] munsell_0.5.0       crayon_1.3.4     
```

**Comment by PoisonAlien** [comment] 2019-12-11 08:36
I have replied it to your email. Do you think you can re-run the command on a different system to see if this is reproducible?

**Comment by likelet** [comment] 2019-12-11 13:41
i will try it in another server and update the result here.

**Comment by likelet** [comment] 2019-12-19 12:04
well, i tried it in another server, it finished in about 3min 
```
-Running NMF for 6 ranks
Compute NMF rank= 4  ... + measures ... OK
Compute NMF rank= 5  ... + measures ... OK
Compute NMF rank= 6  ... + measures ... OK
-Finished in 00:03:24 elapsed (12.8s cpu) 
```
here is the `sessionInfo` in this server,  so i think the first server should be not properly configured 
```R
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] NMF_0.21.0                        Biobase_2.40.0                   
 [3] cluster_2.0.7-1                   rngtools_1.3.1                   
 [5] pkgmaker_0.27                     registry_0.5                     
 [7] BSgenome.Hsapiens.UCSC.hg19_1.4.0 BSgenome_1.48.0                  
 [9] rtracklayer_1.40.6                Biostrings_2.48.0                
[11] XVector_0.20.0                    GenomicRanges_1.32.7             
[13] GenomeInfoDb_1.16.0               IRanges_2.14.12                  
[15] S4Vectors_0.18.3                  BiocGenerics_0.26.0              
[17] maftools_2.2.10                  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3                  lattice_0.20-35            
 [3] Rsamtools_1.32.3            assertthat_0.2.0           
 [5] digest_0.6.18               foreach_1.4.4              
 [7] gridBase_0.4-7              R6_2.3.0                   
 [9] plyr_1.8.4                  ggplot2_3.1.0              
[11] pillar_1.4.2                zlibbioc_1.26.0            
[13] rlang_0.4.2                 lazyeval_0.2.1             
[15] data.table_1.12.8           Matrix_1.2-14              
[17] splines_3.5.1               BiocParallel_1.14.2        
[19] stringr_1.3.1               RCurl_1.95-4.11            
[21] munsell_0.5.0               DelayedArray_0.6.6         
[23] compiler_3.5.1              pkgconfig_2.0.2            
[25] tidyselect_0.2.5            SummarizedExperiment_1.10.1
[27] tibble_2.1.3                GenomeInfoDbData_1.1.0     
[29] codetools_0.2-15            matrixStats_0.54.0         
[31] XML_3.98-1.16               crayon_1.3.4               
[33] dplyr_0.8.3                 withr_2.1.2                
[35] GenomicAlignments_1.16.0    bitops_1.0-6               
[37] grid_3.5.1                  xtable_1.8-3               
[39] gtable_0.2.0                magrittr_1.5               
[41] scales_1.0.0                bibtex_0.4.2               
[43] stringi_1.2.4               reshape2_1.4.3             
[45] doParallel_1.0.14           wordcloud_2.6              
[47] RColorBrewer_1.1-2          iterators_1.0.10           
[49] tools_3.5.1                 glue_1.3.0                 
[51] purrr_0.3.3                 survival_2.42-3            
[53] colorspace_1.3-2     
```
Therefore, i think the best solution for this is to change another server:)

**Comment by PoisonAlien** [comment] 2019-12-19 13:48
Thank you for checking it :) I wonder what must have gone wrong with the old cluster. 
Anyway, I am closing the issue for now. Please feel free to reopen if necessary.

**Closed** 2019-12-19 13:49 UTC
