### ISSUE TITLE
Problem when trying to install maftools on Mac

### ISSUE THREAD

**Issue by sandmanns** [PoisonAlien/maftools#886] opened 2022-12-14 11:19 UTC
**Describe the issue**

We are currently experiencing a problem when trying to install maftools on Mac. The installation of the "normal" Bioconductor package "maftools" seems to work, but when we try to load it, there seems to be a problem with DNAcopy.so. We tried to install the package DNAcopy manually, then again maftools, but the error remains. Unfortunately, we experience the same error when trying to install "PoisonAlien/maftools". 
Thanks a lot in advance for your help!

**Command**

```
> BiocManager::install("maftools",force=T)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'maftools'
trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/maftools_2.14.0.tgz'
Content type 'application/x-gzip' length 11567249 bytes (11.0 MB)
==================================================
downloaded 11.0 MB


The downloaded binary packages are in
	/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T//Rtmp8t6yAm/downloaded_packages

> library("maftools")
Error: package or namespace load failed for ‘maftools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'
> BiocManager::install("DNAcopy",force=T)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'DNAcopy'
trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/DNAcopy_1.72.1.tgz'
Content type 'application/x-gzip' length 510684 bytes (498 KB)
==================================================
downloaded 498 KB


The downloaded binary packages are in
	/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T//Rtmp8t6yAm/downloaded_packages


> BiocManager::install("maftools",force=T)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'maftools'
trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/maftools_2.14.0.tgz'
Content type 'application/x-gzip' length 11567249 bytes (11.0 MB)
==================================================
downloaded 11.0 MB


The downloaded binary packages are in
	/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T//Rtmp8t6yAm/downloaded_packages

> library("maftools")
Error: package or namespace load failed for ‘maftools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'

> BiocManager::install("PoisonAlien/maftools",force=T)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing github package(s) 'PoisonAlien/maftools'
Downloading GitHub repo PoisonAlien/maftools@HEAD
✔  checking for file ‘/private/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T/Rtmp8t6yAm/remotes109d7f7f267f/PoisonAlien-maftools-1c64bf9/DESCRIPTION’ ...
─  preparing ‘maftools’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘maftools_2.12.05.tar.gz’
   
* installing *source* package ‘maftools’ ...
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhtslib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zlibbioc/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ntcounts.c -o ntcounts.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhtslib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zlibbioc/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c snpcounts.c -o snpcounts.o
snpcounts.c:56:26: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  int nloci = countlines(bedfile);
                         ^~~~~~~
snpcounts.c:13:22: note: passing argument to parameter 'filename' here
int countlines(char *filename){
                     ^
snpcounts.c:56:7: warning: unused variable 'nloci' [-Wunused-variable]
  int nloci = countlines(bedfile);
      ^
2 warnings generated.
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhtslib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zlibbioc/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c somaticfreq.c -o somaticfreq.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o maftools.so ntcounts.o snpcounts.o somaticfreq.o /Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhtslib/usrlib/libhts.a -lcurl -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-maftools/00new/maftools/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘maftools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/maftools’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/maftools’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T//Rtmp8t6yAm/file109d18ef3832/maftools_2.12.05.tar.gz’ had non-zero exit status
```

**Session info**
```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.7.2            prettyunits_1.1.1   crayon_1.5.2        withr_2.5.0        
 [5] rprojroot_2.0.3     R6_2.5.1            cli_3.4.1           curl_4.3.3         
 [9] rstudioapi_0.14     remotes_2.4.2       callr_3.7.3         tools_4.2.2        
[13] compiler_4.2.2      processx_3.8.0      pkgbuild_1.3.1      BiocManager_1.30.19

```

**Comment by lizabethkatsnelson** [comment] 2022-12-20 16:51
@sandmanns any luck on resolving this issue? i've been having the same problem and have not been able to find a solution yet.

**Comment by sandmanns** [comment] 2022-12-20 16:58
@lizabethkatsnelson not yet - unfortunately. But good to see that we are not alone :-)

**Comment by ShixiangWang** [comment] 2022-12-21 00:03
when you install any package，restart
 r session every time

**Comment by lizabethkatsnelson** [comment] 2022-12-21 03:56
@ShixiangWang the problem is that it won't install properly. i've tried restarting but that doesnt solve the issue. i think it's an issue with gfortran https://github.com/nullranges/nullranges/issues/20

**Comment by ShixiangWang** [comment] 2022-12-22 03:08
@lizabethkatsnelson This is actually an install issue of DNAcopy. Could you try installing the source package locally?

e.g.,

```r
BiocManager::install("DNAcopy", type = "source")
```

**Comment by sandmanns** [comment] 2022-12-22 11:19
@ShixiangWang We just tried:

```
> BiocManager::install("DNAcopy", type = "source")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'DNAcopy'
trying URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/DNAcopy_1.72.2.tar.gz'
Content type 'application/x-gzip' length 297973 bytes (290 KB)
==================================================
downloaded 290 KB

* installing *source* package ‘DNAcopy’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c cbsWtstats.f -o cbsWtstats.o
make: gfortran: No such file or directory
make: *** [cbsWtstats.o] Error 1
ERROR: compilation failed for package ‘DNAcopy’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy’

The downloaded source packages are in
	‘/private/var/folders/bx/n5y8wbvx6td4rk2q0ht795lm0000gn/T/Rtmp5IrMpz/downloaded_packages’

Warning message:
In install.packages(...) :
  installation of package ‘DNAcopy’ had non-zero exit status
> library(DNAcopy)
Error: package or namespace load failed for ‘DNAcopy’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'
```

Does anyone maybe have any further ideas? Thanks a lot in advance!

**Comment by ShixiangWang** [comment] 2022-12-22 14:58
@sandmanns You have to install compile tools for this. https://mac.r-project.org/tools/

**Comment by Susung-CMU** [comment] 2023-01-03 23:04
The same problem, install the following and it works.
BiocManager::install("DNAcopy", type = "source",force=TRUE)

**Comment by yangtao38324** [comment] 2023-01-16 08:03
I also encountered the same problem, have you solved it?

**Comment by Susung-CMU** [comment] 2023-01-16 14:22
> I also encountered the same problem, have you solved it?

Yes, solved it, you could remove "DNAcopy" first and installl again.

**Comment by lizabethkatsnelson** [comment] 2023-01-16 17:25
still not working for me. it's a compiling issue with gfortran

**Comment by yangtao38324** [comment] 2023-01-17 03:00
> > I also encountered the same problem, have you solved it?
> 
> Yes, solved it, you could remove "DNAcopy" first and installl again.


Unfortunately, I still have a similar problem with @sandmanns .
```{r}
> BiocManager::install("DNAcopy")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://mirrors.tuna.tsinghua.edu.cn/CRAN/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'DNAcopy'
trying URL ’https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/DNAcopy_1.72.2.tgz'
Content type 'application/x-gzip' length 510742 bytes (498 KB)
==================================================
downloaded 498 KB


The downloaded source packages are in
	/var/folders/ld/0fvrf66n0jg9__60gm51x3_00000gn/T//Rtmpi4vxH7/downloaded_packages
> library(DNAcopy)
Error: package or namespace load failed for ‘DNAcopy’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at)
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so'
  Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib'
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.19 compiler_4.2.2      fastmap_1.1.0       cli_3.6.0           htmltools_0.5.4     tools_4.2.2        
 [7] rstudioapi_0.14     yaml_2.3.6          rmarkdown_2.19      knitr_1.41          xfun_0.36           digest_0.6.31      
[13] rlang_1.0.6         evaluate_0.19

**Comment by yangtao38324** [comment] 2023-01-17 03:01
> still not working for me. it's a compiling issue with gfortran

I reinstalled gfortran and the problem still exists

**Comment by ShixiangWang** [comment] 2023-01-17 03:25
Did you install the gfortran first and then install the DNAcopy with source mode?

**Comment by yangtao38324** [comment] 2023-01-17 08:06
> Did you install the gfortran first and then install the DNAcopy with source mode?

After I installed gfortran, I uninstalled DNAcopy and then reinstalled it. But it still doesn't work. 
Is there a problem with the R version？

**Comment by guriaregojo** [comment] 2023-01-17 08:46
Hello I'm having a similar problem: I'm running github actions on a new R package I'm making and in macOS I am getting an error when running maftools::read.maf, specifically the issue is related to this DNAcopy package and gfortran. I attach a picture of the failed job:
<img width="714" alt="Screenshot 2023-01-17 at 09 40 51" src="https://user-images.githubusercontent.com/73877383/212850501-f49cc04a-904c-4290-b16a-38dd6ad0dbe3.png">
Do you have any idea on how to fix this for a new R pacakage?
Thank you

**Comment by orzechmag** [comment] 2023-01-17 12:46
Guys,
I experienced exactly the same problem and was really frustrated with no solution. Anyway, from my research it looked like the versions of installed gcc, gfortran, and clang are not compatible with each other. For me did work:
1. updating clang (whatever else) with brew upgrade,
2. installing CommandLineTools with sudo rm -rf /Library/Developer/CommandLineTools xcode-select --install
3. installing gfortran from https://mac.r-project.org/tools/ for Mojave (even though I am MacOS Monterey)
4. installing DNAcopy from source as suggested by @Susung-CMU 
5. restarting R session
6. maftools, TCGAWorkflow and the other DNAcopy-dependent packages are working perfectly fine!
I keep my fingers crossed for your cases. I hope it helps.

**Comment by LiNk-NY** [comment] 2023-01-17 19:04
Hi all, 
Have you tried to install gfortan as shown here? 
https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#27-install-gfortran
This is how the Bioconductor Mac builders install their `gfortran`. 
-Marcel

**Comment by guriaregojo** [comment] 2023-01-17 20:20
@LiNk-NY Hi Marcel I'm building a new package for bioconductor and I'm using github actions biocthis::use_bioc_github_action()  to check my package. I'm getting the gfortran error for macOS but ubuntu and windows checks are running fine. Can I contribute my package assuming that when the bioconductor team checks my package they won't have this problem with macOS? Or should I edit something regarding gfortran in my check-bioc.yml workflow?
Thank you for your help

**Comment by LiNk-NY** [comment] 2023-01-17 20:25
Hi Graciela, @guriaregojo 

Yes, you can submit the package. It will be tested on the Single Package Builder (SPB) and if the error persists we will help you remedy it. 

You could also try `rworkflows` which claims to solve some of these issues of managing dependencies for GHA: https://github.com/marketplace/actions/rworkflows

Best,
Marcel

**Comment by guriaregojo** [comment] 2023-01-17 20:37
Great! Thank you again Marcel @LiNk-NY

**Comment by ca-tapia** [comment] 2023-01-17 22:02
Hi everyone!
I had the same problem, and the way could solve it was deleting DNAcopy package and then downloaded .tgz files for both DNAcopy and maftools and installed it. 
I have to say that I am using a Macbook with a M1 processor and R through Rstudio.

```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_2.1.3     stringr_1.5.0   ggplot2_3.4.0   dplyr_1.0.10   
[5] devtools_2.4.5  usethis_2.1.6   readxl_1.4.1    maftools_2.14.0

```

I hope this info can help :)

**Comment by jwokaty** [comment] 2023-01-18 21:47
There's an issue with gfortran on the 3.16 Intel Mac Bioconductor builder, such that it's not properly bundling the gfortran library with the binary. I corrected the version of gfortran on the machine, but it will take a few days to propagate the packages. They should be updated next week. Thanks for your patience.

**Comment by m-mahgoub** [comment] 2023-01-20 01:34
> Guys,
> I experienced exactly the same problem and was really frustrated with no solution. Anyway, from my research it looked like the versions of installed gcc, gfortran, and clang are not compatible with each other. For me did work:
> 1. updating clang (whatever else) with brew upgrade,
> 2. installing CommandLineTools with sudo rm -rf /Library/Developer/CommandLineTools xcode-select --install
> 3. installing gfortran from https://mac.r-project.org/tools/ for Mojave (even though I am MacOS Monterey)
> 4. installing DNAcopy from source as suggested by @Susung-CMU 
> 5. restarting R session
> 6. maftools, TCGAWorkflow and the other DNAcopy-dependent packages are working perfectly fine!
> I keep my fingers crossed for your cases. I hope it helps.
> 

That worked... Thanks!

**Comment by jwokaty** [comment] 2023-01-20 18:56
There's a new version of DNAcopy (1.72.3) available for Bioconductor 3.16. If anyone with an Intel Mac who tries to reinstall with this new version and is still having issues, I would be interested in troubleshooting.

**Comment by m-mahgoub** [comment] 2023-01-20 20:29
> Guys, I experienced exactly the same problem and was really frustrated with no solution. Anyway, from my research it looked like the versions of installed gcc, gfortran, and clang are not compatible with each other. For me did work:
> 
> 1. updating clang (whatever else) with brew upgrade,
> 2. installing CommandLineTools with sudo rm -rf /Library/Developer/CommandLineTools xcode-select --install
> 3. installing gfortran from https://mac.r-project.org/tools/ for Mojave (even though I am MacOS Monterey)
> 4. installing DNAcopy from source as suggested by @Susung-CMU
> 5. restarting R session
> 6. maftools, TCGAWorkflow and the other DNAcopy-dependent packages are working perfectly fine!
>    I keep my fingers crossed for your cases. I hope it helps.

This worked! Thanks

**Comment by yangtao38324** [comment] 2023-01-31 09:12
> Guys, I experienced exactly the same problem and was really frustrated with no solution. Anyway, from my research it looked like the versions of installed gcc, gfortran, and clang are not compatible with each other. For me did work:
> 
> 1. updating clang (whatever else) with brew upgrade,
> 2. installing CommandLineTools with sudo rm -rf /Library/Developer/CommandLineTools xcode-select --install
> 3. installing gfortran from https://mac.r-project.org/tools/ for Mojave (even though I am MacOS Monterey)
> 4. installing DNAcopy from source as suggested by @Susung-CMU
> 5. restarting R session
> 6. maftools, TCGAWorkflow and the other DNAcopy-dependent packages are working perfectly fine!
>    I keep my fingers crossed for your cases. I hope it helps.

@orzechmag This worked! Thanks

**Comment by sandmanns** [comment] 2023-08-04 02:09
I am currently out of office. I will be back by August, 14th. Your
    mails will not be forwarded. In case of emergency, please contact my
    colleague Carolin Walter ***@***.***).

**Closed** 2023-09-18 08:46 UTC
