### ISSUE TITLE
read.maf Fails If Run Twice

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#438] opened 2019-12-05 03:00 UTC
```r
> HNSCexomeMutations <- read.maf("TCGA.HNSC.muse.225a3a8f-27fd-4d9f-b8af-4eadbae9304e.DR-10.0.somatic.maf",
                                  cnTable = copyTableTCGA,
                                  clinicalData = allClinicalTable, isTCGA = TRUE)
-Reading
-Validating
-Silent variants: 29979 
-Processing copy number data
-Summarizing
--Possible FLAGS among top ten genes:
  TTN
  MUC16
  SYNE1
-Processing clinical data
--Annotation missing for below samples in MAF:
  TCGA-BA-4075
  TCGA-BA-4076
  TCGA-BA-4077
  TCGA-BA-4078
  TCGA-BA-5151
-Finished in 8.400s elapsed (8.140s cpu)

> HNSCexomeMutations <- read.maf("TCGA.HNSC.muse.225a3a8f-27fd-4d9f-b8af-4eadbae9304e.DR-10.0.somatic.maf",
                                 cnTable = copyTableTCGA,
                                 clinicalData = allClinicalTable, isTCGA = TRUE)
-Reading
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  Opened 0TB (122325916 bytes) file ok but could not memory map it. This is a 32bit process. Please upgrade to 64bit.
```

Is there a way to avoid the flaky `data.table` package?

```r
R version 3.6.1 (2019-07-05)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1
```

**Comment by ShixiangWang** [comment] 2019-12-05 03:14
This error cannot be reproduced.

```
> library(maftools)
> laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
> laml <- read.maf(maf = laml.maf)
-Reading
-Validating
-Silent variants: 475 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.226s elapsed (0.756s cpu) 
> laml <- read.maf(maf = laml.maf)
-Reading
-Validating
-Silent variants: 475 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.463s elapsed (1.320s cpu) 
> laml2 <- read.maf(maf = laml.maf)
-Reading
-Validating
-Silent variants: 475 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.213s elapsed (0.758s cpu) 
```

I think if your file is very big but your memory is not enough to read it again.

May you try `rm(HNSCexomeMutations); gc()` before reading it again?

**Comment by DarioS** [comment] 2019-12-05 04:00
It's only 116 MB. It would be fine as a plain `data.frame` but data.table is resource-hungry. Your code to free some memory works, though.

**Comment by PoisonAlien** [comment] 2019-12-13 12:47
I am closing issue since this not directly related to maftools itself.

**Closed by PoisonAlien** 2019-12-13 12:47 UTC
